#!/usr/bin/env ruby

version File.read('VERSION').strip

name    "bang"
title   "Bang! Bang!"
summary "Bang methods for assertions!"
created '2012-01-26'

description "Bang Bang provides an assertion grammar utlizing bang methods and
built on top of the the Assay assertions system."

authors [
  'Thomas Sawyer <transfire@gmail.com>'
]

requirements [
  'brass',
  'detroit (build)',
  'qed     (test)'
]

resources(
  'home' => 'http://rubyworks.github.com/bang',
  'code' => 'http://github.com/rubyworks/bang',
  'mail' => 'http://groups.google.com/groups/rubyworks-mailinglist'
)

repositories(
  'upstream' => 'git@github.com:rubyworks/bang.git'
)

copyrights [
  '2012 Rubyworks (BSD-2-Clause)'
]

organization 'Rubyworks'

